# Generated by Django 3.1 on 2020-08-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('roll', models.CharField(max_length=9, null=True)),
                ('dept', models.CharField(choices=[('cs', 'cse'), ('cv', 'civil'), ('mech', 'mech'), ('prod', 'prod'), ('met', 'meta'), ('ee', 'eee'), ('ec', 'ece')], max_length=10, null=True)),
            ],
        ),
    ]
