# Generated by Django 3.1 on 2020-08-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordbook', '0003_remove_student_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dept',
            field=models.CharField(choices=[('CSE', 'cse'), ('Civil', 'civil'), ('Mechanical', 'mech'), ('Production', 'prod'), ('Metallurgy', 'meta'), ('EEE', 'eee'), ('ECE', 'ece')], max_length=10, null=True),
        ),
    ]
